import Footer from "@/components/layout/footer";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"h-full bg-background antialiased flex flex-col",
					GeistSans.className,
				)}
			>
				<main className="container mx-auto flex-1 pb-12">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
